name: C compile and run testing
on: [push]
jobs:
  root-dir:
    runs-on: ubuntu-latest
    steps: 
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Compile C in root folder
        run: gcc root_test.c -o main
      - run: echo "🎉 Compile successful"
      - name: Run C in root folder
        run: ./main
      - run: echo "🎉 Run successful"

  folder-dir:
    runs-on: ubuntu-latest
    steps: 
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Move to folder
        run : |
          pwd
          cd folder1
          pwd
      - name: Compile C in sub folder
        run: |
          pwd
          cd folder1
          pwd
          gcc folder_test.c -o main_sub
      - run: echo "🎉 Compile successful"
      - name: Run C in sub folder
        run: ./main_sub
      - run: echo "🎉 Run successful"