name: C compile and run testing
on: 
  push:
    branches: [test_pushAction]
jobs:
  root-dir:
    runs-on: ubuntu-latest
    steps: 
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Compile C in root folder
        run: gcc root_test.c -o main
      - run: echo "🎉 Compile successful"
      - name: Run C in root folder
        run: ./main
      - run: echo "🎉 Run successful"

  folder-dir:
    runs-on: ubuntu-latest
    steps: 
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Compile C in sub folder
        run: gcc ./folder1/folder_test.c -o main_sub
      - run: echo "🎉 Compile successful"
      - name: Run C in sub folder
        run: |
          cd folder1
          ./main_sub
      - run: echo "🎉 Run successful"